### ISSUE TITLE
How do I run the program?

### ISSUE THREAD

**Issue by naterbug25** [onerobotics/fexcel#11]
Silly question I know. After I ran the exe, how do I execute the program? My command terminal does not allow me to run it. 

Thank you.

**Comment by naterbug25** [comment]
I receive: 'fexcel' is not recognized as an internal or external command, operable program or batch file.

**Comment by unreal** [comment]
Hi Nathan,

Thanks for checking out fexel. First make sure the executable is in your working directory (or on your system $PATH). You'll then have to provide the exact name of the exe (e.g. `fexcel-v1.1.0.exe`) before providing arguments. Your command prompt should allow you to use tab completion, so typing something like `fexcel` then hitting the TAB key should get that going for you.

Simply running fexcel without arguments will provide more detailed usage instructions. Let me know if you have any other questions.

**Comment by naterbug25** [comment]
It works great. Thank you!
