### ISSUE TITLE
v2.0.0 Beta - Limited number of lines when comparing data

### ISSUE THREAD

**Issue by NJReich** [onerobotics/fexcel#16]
Is the program limited to around 300 lines?

When I send a diff command, I'm comparing my position registers and number registers at the same. Over half of my position registers are cut off. 

Both PR and R are 256 lines long.

**Comment by unreal** [comment]
There's no limit (though maybe that's a good idea, ha). My guess is this is the max buffer size of your command prompt/terminal.

You can either increase your buffer size (right click > Properties), pipe the output through `more` e.g. `fexcel diff spreadsheet.xlsx robot.ip.address | more`, or send the output to a file e.g. `fexcel diff spreadsheet.xlsx robot.ip.address > diff.txt`

Can you let me know if this fixes your issue?

**Comment by NJReich** [comment]
Yes, either command fixed my issues. I like sending the output to a file. 

Thanks

**Comment by unreal** [comment]
I will add a note on this to the README. Thanks!
