### ISSUE TITLE
Can't Compare Items

### ISSUE THREAD

**Issue by NJReich** [onerobotics/fexcel#17]
numregs, posregs, ualms work just fine. 

When I try to compare any other flags it doesn't work. 

Example: 

When I send the command "fexcel diff --rins H3 ROBOT_UPLOAD.xlsx 192.168.2.8"

I get the error message "Get http://192.168.2.8/md/iostate.dg_TEMPLATE=: net/htp: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by unreal** [comment]
Thanks for testing!

Try increasing the --timeout flag. Maybe the default should be greater than 500 (ms).

**Comment by NJReich** [comment]
That worked! I had to increase my timeout to 1600 ms

**Comment by unreal** [comment]
Does your robot have an unusual amount of I/O?

I will also test next time I get my hands on a busy robot to see if the default timeout should be increased.

**Comment by NJReich** [comment]
Not really. 

I was seeing this issue when trying to compare robot inputs/outputs. I only have a comment for #1 & #2

**Comment by NJReich** [comment]
Not really.

I was seeing this issue when trying to compare robot inputs/outputs. I only have a comment for RI/RO 1 & 2

**Comment by unreal** [comment]
fexcel uses a [go-fanuc][1] [HTTPClient][2] behind the scenes to grab and parse iostage.dg for any I/O request (DI/DO/RI/RO/etc) to get comments. I would expect you to see the same timeout for any I/O diff.

This file is somewhat large, and perhaps the robot is not great at generating it (though go-fanuc does cache the result for subsequent IO requests).

Parsing iostage.dg with regex is probably the least performant way to get the data we want here, but the only other (public) API for grabbing I/O comments is the FANUC web Comment Tool itself... maybe worth investigating for fun.

[1]: https://github.com/onerobotics/go-fanuc
[2]: https://github.com/onerobotics/go-fanuc/blob/master/http_client.go

**Comment by unreal** [comment]
I think it's probably a good idea to increase the default timeout to 2000ms or more, but I'll have do some some testing on the real robot.

The downside would be waiting 2s trying to connect to an unreachable robot, but I can modify the underlying net.Dialer.Timeout (default 30s!) for this case.

**Comment by unreal** [comment]
@NJReich do you mind testing the [latest release](https://github.com/onerobotics/fexcel/releases/tag/v2.0.0-beta.2)? I bumped the default timeout all the way up to 5 seconds.

**Comment by NJReich** [comment]
I'll download it right now!

**Comment by NJReich** [comment]
No issues when comparing comments. The 5-second timeout seems to have fixed the issue. 

When testing the first version of 2.0.0 Beta 2s also worked.

**Comment by NJReich** [comment]
![2020-01-17 16_24_54-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/33013659/72650597-90ea7580-3946-11ea-9e5b-eb2df59d8fae.png)

**Comment by unreal** [comment]
@NJReich I've decided to take v2.0 closed source. Much of the tool will still be free (e.g. all the tools you've seen so far in the beta), but I have some ideas for a premium version. Shoot me an email if you want to discuss further.

**Comment by unreal** [comment]
@NJReich just pinging you because I've done an about-face on the closed-source v2.0 and pushed it here[1] in case you want to take a look.

[1]: https://github.com/onerobotics/fexcel/tree/dev
