### ISSUE TITLE
Set Command failed to update error

### ISSUE THREAD

**Issue by NJReich** [onerobotics/fexcel#18]
When using the set command I'm getting the following message:

![2020-01-17 16_24_54-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/33013659/72650640-b5465200-3946-11ea-84bf-3f30764b5888.png)

I got this error message when I'm tried to update/change comments. The comments on the robot do get updated. If I try running the set command again I will simply get:

![2020-01-17 16_31_23-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/33013659/72650706-dad35b80-3946-11ea-8ad4-6e4a5370c21b.png)

**Comment by unreal** [comment]
My bad. Forgot to change the units on the actual comment update, so it was getting a 5ms timeout. https://github.com/onerobotics/fexcel/blob/8dae6cf62460122dea6a9efeaa1d5f44a24af76d/cmd/set.go#L96

This is a good excuse to pull comtool into go-fanuc anyway.

**Comment by unreal** [comment]
Should be fixed by the [latest release](https://github.com/onerobotics/fexcel/releases/tag/v2.0.0-beta.3). Thanks again for testing!
