### ISSUE TITLE
Set cmd "invalid syntax"

### ISSUE THREAD

**Issue by benxi1** [onerobotics/fexcel#19]
![image](https://user-images.githubusercontent.com/86303422/122929823-a9e12c80-d36b-11eb-96c7-561b9b11d195.png)

I got "invalid syntax" when using the set command. I have tested with the "test.xlsx" spreadsheet available on GitHub.
Could it be because I don't use the same Windows settings (languages / keyboard...?) If yes which one should I use?

I have tested create command and it works fine

Thank you

**Comment by unreal** [comment]
Hi, thanks for trying fexcel. Fexcel expects numeric port ids to be in the
column you specify, and the comments in that column + the defined offset
(default 1).

It looks like your spreadsheet has non-numeric IDs like "rin1" which it's
having trouble parsing. Try changing that column to simply 1, 2, 3, etc.  I
usually have a header e.g. "RI" in say F1 and then tell fexcel to look at
the IDs starting in F2.

**Comment by benxi1** [comment]
My bad, I was specifying columns containing comments and not numeric IDs...Thank you for this great tool!

**Comment by unreal** [comment]
Awesome, glad it's useful to you!
