### ISSUE TITLE
Use with Roboguide

### ISSUE THREAD

**Issue by NJReich** [onerobotics/fexcel#26]
What is the trick for using fexcel with Roboguide? I thought this could be done in the past. This is the current error I see when I try to upload to 127.0.0.2 virtual robot. 

Error: 127.0.0.2: Request failed: "http://127.0.0.2/MD/iostate.dg?_TEMPLATE=" (404)

![image](https://user-images.githubusercontent.com/33013659/166524757-476e00bd-4a83-430c-a575-5e54faeb3db2.png)

**Comment by unreal** [comment]
Sorry for the late reply. There's no trick to using with ROBOGUIDE; it should just work.

Is the robot webpage reachable?

**Comment by NJReich** [comment]
No worries. Yes the robot webpage is reachable. 

I just tried to use fexel on a different computer with Roboguide and it worked. I'm not sure why it didn't work on my first computer. I'll need to look into it.

**Comment by NJReich** [comment]
On the computer that doesn't work. I can't access the webpage by just typing the IP address 127.0.0.2. When I try accessing the page webpage via Roboguide it will add port 9000 to the IP address. 

![image](https://user-images.githubusercontent.com/33013659/168154847-7517bc96-83bd-4332-b89c-fcc9c7f6005a.png)

**Comment by unreal** [comment]
Try giving your robot another ip address from the virtual TP e.g. `127.0.0.101`

edit:
Go to `Menu > Setup > Host Comm` and give port 1 that ip address, then cycle power. You should be able to see the robot webpage at http://127.0.0.101 without a special port number.

**Comment by unreal** [comment]
Adding on to this:

ROBOGUIDE seems to give all new virtual robots the 127.0.0.1 IP address. The various services (e.g. web server, ftp server, etc.) are then given available ports in the 9000 range.

If you give the robot a unique ip address the web server will use the standard port 80 that fexcel expects.

**Comment by NJReich** [comment]
127.0.0.101 Didn't work. It's still adding the port number. It looks like on my computer every 127.0.0.x number is bringing me to this page: 

![image](https://user-images.githubusercontent.com/33013659/168159897-90feabaf-3a76-495c-aa27-c397ffd0eb22.png)

**Comment by unreal** [comment]
Can you verify that virtual robot is using that IP with robot neighborhood?

It could be that IIS is hijacking port 80 no matter what. You could try disabling the windows service and rebooting your robot?

Alternatively fexcel and https://github.com/onerobotics/go-fanuc would have to support ip address with ports.

**Comment by NJReich** [comment]
I'd tried to disable IIS and I'm not having any luck. I might try to remove it. 

![image](https://user-images.githubusercontent.com/33013659/168166705-b220feea-32ec-4501-b080-baacc7517dad.png)

![image](https://user-images.githubusercontent.com/33013659/168166931-ada10607-57fb-458f-95ca-69b574aaa475.png)

**Comment by NJReich** [comment]
Yes, the virtual robot's IP address is also in Robot Neighborhood.

**Comment by NJReich** [comment]
Uninstalling IIS did the trick! 
Earlier, I tried to disable IIS services and that didn't work. I had to uninstall IIS from the windows features. 

Thanks for your support.

**Comment by unreal** [comment]
Glad you got it working!
