### ISSUE TITLE
Needed to specify a port but could not.  fanuc.HTTP was hard coded.

### ISSUE THREAD

**Issue by PaulR1978** [onerobotics/fexcel#27]
It would be great if we had access to specify the port.  Either put the port directly in the IP address or specify by putting --port.  I needed to push to a Roboguide robot with a profient configuration.  Only way is to specify would have been to specify a non standard port (9006) for it to go through roboguide.

**Comment by unreal** [comment]
Hi Paul,

Fexcel actually uses a go-fanuc[1] Client under the hood, which supports IP address or URLs. Try tossing a URL to fexcel e.g. `> fexcel set ./path/to/spreadsheet.xlsx http://localhost:9006 --flags`
