### ISSUE TITLE
add a -diff option?

### ISSUE THREAD

**Issue by unreal** [onerobotics/fexcel#9]
I'd like to be able to compare what's currently on the robot vs. what's in my spreadsheet.

**Comment by NJReich** [comment]
This would be a nice feature to have. OR just upload what's in the robot to a spreadsheet.

**Comment by unreal** [comment]
Working on it. I should say that this will introduce breaking changes in fexcel usage, so this will be in v2.0.0.

**Comment by unreal** [comment]
See dev branch.
Usage: `fexcel diff ./path/to/spreadsheet.xlsx target(s)... [flags]`

e.g. `fexcel diff ./fexcel/testdata/test.xlsx 127.0.0.1 ./fexcel/testdata/ --numregs Data:A2`

produces a table like this:

    Numeric Registers
    +----+------+-----------------------------------+------------------+--------------------+
    | Id | Diff |             test.xlsx             |    127.0.0.1     | ./fexcel/testdata/ |
    +----+------+-----------------------------------+------------------+--------------------+
    |  1 | X    | this is an extremely long comment | this is an extre | this is an extre   |
    |  2 |      | two                               | two              | two                |
    |  3 |      | three                             | three            | three              |
    |  4 | X    | four                              | four             | f                  |
    |  5 |      | five                              | five             | five               |
    +----+------+-----------------------------------+------------------+--------------------+

**Comment by NJReich** [comment]
Awesome! I love the v2.0.0 Beta! This is such a great tool. Thank You!
